language: objective-c
osx_image: xcode7.3

script:
- xcodebuild clean build test -project "Sample Project/CheckBox.xcodeproj" -scheme CheckBox -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 5S" ONLY_ACTIVE_ARCH=NO
